### ISSUE TITLE
引入插件报错

### ISSUE THREAD

**Issue by sansansine** [simple-uploader/vue-uploader#1]
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/xiangchengli678/vogue/node_modules/vue-simple-uploader/.babelrc" at 1, attempted to resolve relative to "/Users/xiangchengli678/vogue/node_modules/vue-simple-uploader"不懂是什么原因？

**Comment by dolymood** [comment]
多谢反馈；
已经移除了 package.json 中的 module 入口，因为webpack2+的版本会默认找 module 作为 es6 作为入口，但是这种场景下不大适合，所以在 0.0.5 版本删除了，升级到 0.0.5 即可。
