### ISSUE TITLE
多语言

### ISSUE THREAD

**Issue by joshualzb** [simple-uploader/vue-uploader#10]
上传提示{success，error，uploading，paused，waiting}怎么配置多语言？

**Comment by dolymood** [comment]
暂时还没支持，这个我来加下

**Comment by joshualzb** [comment]
我已经修改了一版，是直接修改文字的，不是提供接口的。
需要的可以临时使用一下
https://github.com/joshualzb/vue-uploader

**Comment by dolymood** [comment]
@joshualzb  是不是也有剩余时间需求？

**Comment by dolymood** [comment]
0.4.0 已修

https://github.com/simple-uploader/vue-uploader/blob/master/README_zh-CN.md#props 这里的 parseTimeRemaining 可以用， 以及 fileStatusText 这个映射表
