### ISSUE TITLE
大佬，你好！options配置中target参数可以不传吗？想自定义操作~~

### ISSUE THREAD

**Issue by xiang0308** [simple-uploader/vue-uploader#102]

**Comment by dolymood** [comment]
target 可以是函数 返回上传地址 应该是你想要的

**Comment by ramseyfeng** [comment]
> target 可以是函数 返回上传地址 应该是你想要的
> 
> 如果是自定义 ajax 上传的话 就暂时是不支持的

现在支持自定义上传了吗？想用这个调用oss大文件的上传
