### ISSUE TITLE
无法分批多次上传 Unable to upload files multiple times

### ISSUE THREAD

**Issue by vegchic** [simple-uploader/vue-uploader#108]
第一次上传没问题，但是如果不把成功后的文件删掉就不能第二次上传，表现是选了文件会没反应，从控制台上看触发了 file-added 的事件，但是 payload 是一个有长度的空数组

**Comment by dolymood** [comment]
https://github.com/simple-uploader/Uploader/blob/develop/README_zh-CN.md#%E9%85%8D%E7%BD%AE

> allowDuplicateUploads 如果说一个文件以及上传过了是否还允许再次上传。默认的话如果已经上传了，除非你移除了否则是不会再次重新上传的，所以也就是默认值为 false。
