### ISSUE TITLE
上传地址改变后，还是使用的第一次初始化传入的服务器地址

### ISSUE THREAD

**Issue by bolingsun** [simple-uploader/vue-uploader#115]
项目中的服务器地址是动态分配的，在options设置target后，第一次上传到服务器地址1，再次使用上传，这次给options的target设置了新的服务器地址2，但是，上传，还是上传到服务器地址1。目前除了使用v-if来强制初始化新的上传实例外，有没有其他的解决办法？

**Comment by dolymood** [comment]
target 可以是函数 用函数来做吧

**Comment by Weili17** [comment]
> target 可以是函数 用函数来做吧

用函数的方法怎么做呀？？
