### ISSUE TITLE
Query parameter "chunk..." automatically append to url, leading to a signature verificiation failed on aws s3.

### ISSUE THREAD

**Issue by Warmriver** [simple-uploader/vue-uploader#119]
Uploader automatically add some query strings to url make aws s3 signed url failed to verify. Cannot find a way to avoid these query parameters when using "octet".
![image](https://user-images.githubusercontent.com/19277554/88144506-985b4600-cc2b-11ea-8c4b-ca3b38d0d3a4.png)

**Comment by dolymood** [comment]
You can use `processParams ` to custom your own params
