### ISSUE TITLE
插件使用问题

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [simple-uploader/vue-uploader#122]
这个插件怎么样使用，后端怎么样接收前端的参数，file对象如何传递给后端，这个能不能说明一下，现在用起来的真的很难

**Comment by dolymood** [comment]
https://github.com/simple-uploader/vue-uploader/blob/master/README_zh-CN.md#%E7%AC%94%E8%AE%B0%E5%91%A8%E8%BE%B9
