### ISSUE TITLE
文件上传一半失败后再执行重新上传，为什么状态直接变成了“上传成功“啊

### ISSUE THREAD

**Issue by lowe21** [simple-uploader/vue-uploader#124]
![image](https://user-images.githubusercontent.com/3894346/93559874-52b0c480-f9b3-11ea-8f5b-ad1397357cd4.png)
![image](https://user-images.githubusercontent.com/3894346/93559929-7116c000-f9b3-11ea-98d9-4959f89d05f2.png)

**Comment by dolymood** [comment]
这个状态应该是由后端接口给了成功吧？

**Comment by lowe21** [comment]
不是的
这个视频文件一共156个分片，我是故意在第50个分片的时候报的500错误，然后点重新上传状态就变成了“上传成功“，到第50个分片的时候又变成了“上传失败“

**Comment by dolymood** [comment]
test逻辑？
需要看你怎么配置的

**Comment by lowe21** [comment]
`
uploaderOptions: {

    target: process.env.VUE_APP_BASE_API + '/association/upload/video',
    query: { token: getToken() },
    singleFile: true,
    chunkSize: 4194304,
    forceChunkSize: true,
    fileParameterName: 'filePart',
    maxChunkRetries: undefined,
    parseTimeRemaining: (timeRemaining, parsedTimeRemaining) => {
        return parsedTimeRemaining.replace(/\syears?/, '年').replace(/\days?/, '天').replace(/\shours?/, '小时').replace(/\sminutes?/, '分钟').replace(/\sseconds?/, '秒')
    },
    checkChunkUploadedByResponse: (chunk, result) => {
        try {
            result = JSON.parse(result)
            if (result.state) {
                // result.data.chunks 返回已上传成功的分片，格式：1,2,3,4,5,6,7,8
                return result.data.chunks.split(',').indexOf(chunk.offset + 1 + '') >= 0
            } else {
                return false
            }
        } catch (e) {
            console.log(e)
            return false
        }
    },
    processResponse: (response, callback, file, chunk) => {
        try {
            response = response && JSON.parse(response)
            callback(!response.state, response)
            // 分片上传失败清空列表（临时方案）
            if (!response.state) {
                file.cancel()
                this.$message.error('文件上传失败，请重新上传')
            }
        } catch (e) {
            console.log(e)
            file.cancel()
            this.$message.error('文件上传失败，请重新上传')
        }
    }

}
`

**Comment by dolymood** [comment]
默认 testChunks 为 true 这个时候可能要看你的get请求是不是直接成功了
以及貌似 processResponse在 catch 中是没有callback 的，如果做了catch 还是建议 callback(err) 下

**Comment by lowe21** [comment]
![test1](https://user-images.githubusercontent.com/3894346/93735896-1b3f5380-fc11-11ea-9503-5e174f6c77ac.gif)

**Comment by lowe21** [comment]
感谢，我再研究研究吧

**Comment by dolymood** [comment]
可以调试下 感觉第二次的时候 一下发三个get请求还是不对的
有可能是我的代码逻辑有问题

**Comment by Jccsion** [comment]
同样是这个问题，传到一半断网重连，就有这个问题，请问题怎么解决

**Comment by duxw-casjc** [comment]
我也遇到同样的问题，请问大神怎么解决

**Comment by dolymood** [comment]
0.7.6 应该修复了这个问题
