### ISSUE TITLE
暂停上传和再次开始上传原理是怎么样的

### ISSUE THREAD

**Issue by Niofh** [simple-uploader/vue-uploader#126]
暂停上传和再次开始上传原理是怎么样的，比如我上传百分之50停止上传刷新了页面，点击继续上传怎么可以从百分之50上传100%

**Comment by dragonir** [comment]
同问

**Comment by dolymood** [comment]
一般根据文件标识来计算 默认 文件名 + 大小 计算的，再次刷新的时候 服务端根据test 就知道这个文件已经上传了一部分
所以可以略过一部分块的上传
