### ISSUE TITLE
大佬支持 vue3 吗

### ISSUE THREAD

**Issue by Gebitily7** [simple-uploader/vue-uploader#129]

**Comment by dolymood** [comment]
https://github.com/simple-uploader/vue-uploader/pull/169

**Comment by dolymood** [comment]
参考 https://github.com/simple-uploader/vue-uploader/tree/vue3

可以安装 next tag 的版本目前处于 beta 版本

@ygj6  提供支持

**Comment by sweet-works** [comment]
现在支持vue3了吗
