### ISSUE TITLE
在fileAdded和filesAdded之前还有可以拦截的事件吗?当选择的文件夹数量过大浏览器崩溃

### ISSUE THREAD

**Issue by zhdarry** [simple-uploader/vue-uploader#132]
一旦选中了文件夹,似乎直接进的fileAdded事件,然后是filesAdded, 比如我选择的文件夹有三万个文件,想知道这两个事件之前还有可以拦截的事件处理没,或者在fileAdded中如何优化这种用户操作?

**Comment by dolymood** [comment]
可以实验 是因为uploader崩溃 还是因为 input file 本身选择这么多的时候就崩溃了；

**Comment by zhdarry** [comment]
> 可以实验 是因为uploader崩溃 还是因为 input file 本身选择这么多的时候就崩溃了；

input file 会有较短时间的卡顿. uploader加入fileList,files浏览器卡顿时间会很长. 有针对这种场景做出限制加入或优化速度的方法吗.

**Comment by xujiafei** [comment]
> 一旦选中了文件夹,似乎直接进的fileAdded事件,然后是filesAdded, 比如我选择的文件夹有三万个文件,想知道这两个事件之前还有可以拦截的事件处理没,或者在fileAdded中如何优化这种用户操作?

遇到同样问题，请问大佬解决了吗？

**Comment by hankaibo** [comment]
我在这个之前添加了change事件，进行数量判断，但可能使用的姿势不对，虽然在change中取消了cancel()，但依然进入了fileadded事件。

**Comment by dolymood** [comment]
因为这些的时机都在 added 之前 cancel 也是
在没有过 files-added 之前 这些文件都不会加入到列表中 所以做啥都是没有用的
