### ISSUE TITLE
测试接口和上传接口不一样怎么处理

### ISSUE THREAD

**Issue by girlfighting** [simple-uploader/vue-uploader#139]

**Comment by lubanproj** [comment]
能描述具体点么？比如哪个测试接口和哪个上传接口，哪些地方不一样呢

**Comment by girlfighting** [comment]
在每次上传过程的最开始，vue-simple-uploader会发送一个get请求，来问服务器我哪些分片已经上传过了。但是这个get请求的接口怎么设置呢？

**Comment by jinyunxi** [comment]
同问  能不能自己写测试的发起函数

**Comment by dolymood** [comment]
target可以是一个函数 自己决定返回的地址即可
