### ISSUE TITLE
是否支持断点续传呢？

### ISSUE THREAD

**Issue by xiaodoubaoldl** [simple-uploader/vue-uploader#14]
是否支持断点续传呢？

**Comment by dolymood** [comment]
支持啊，分块一个是提升上传速度，一个就是可以做到断点续传。所以会有 testChunks ， checkChunkUploadedByResponse 等options 可以做处理，判断哪些文件块是已经传完的，就不需要传了

**Comment by xiaodoubaoldl** [comment]
问题一：
1、使用maxChunkRetries属性！！！
2、上传过程中断掉node服务或者网掉了当恢复的时候继续上传
以上两种情况都需要打开testChunks对吧？
问题二：
断掉后台服务，或者网断了都会暂停上传，我不去手动点击暂停按钮！当服务恢复后我怎么实现自动继续上传？
目前我看到的状况是必须手动点击一下调用resume（）方法才可以继续


谢大神解答！方便的话留个国内邮箱请教一下

**Comment by dolymood** [comment]
可以使用QQ邮箱 892759578@qq.com
