### ISSUE TITLE
如何修改testChunks接口地址？

### ISSUE THREAD

**Issue by 1161740194** [simple-uploader/vue-uploader#154]
服务器分片校验接口地址和分片上传的地址不同，插件是接口地址相同，请求方式不同，如何修改分片校验接口地址。

**Comment by uncleMrWang** [comment]
请问解决了吗，，我也是这种问题

**Comment by 1161740194** [comment]
> 请问解决了吗，，我也是这种问题
target写成函数，用第三个参数判断下
