### ISSUE TITLE
为什么在files-added或者fileadded做file的验证的时候，不符合我的验证规则的情况还能把<uploader-list>展示出来

### ISSUE THREAD

**Issue by ss7424Refar** [simple-uploader/vue-uploader#157]
比如files的验证中

```
onFilesAdded(files, fileList) {
    // 如果这个文件不符合我的验证规则
    ....   // 这里做了验证代码 
    
    // ignore file
    files.ignore  = true;
    alert('您有个别文件错误');
    return false;

}
```

然后<uploader-list>还会把符合验证规则的文件展示出来.

`我要怎么做才能让只有符合规则的情况下展示文件列表， 不符合的时候弹出自定义消息，并不展示<uploader-list>？`

**Comment by dolymood** [comment]
没明白 如果是单文件 的校验 就是 file-added 中
如果是 多文件或者文件夹 就是files-added 处理

且处理的逻辑是设置 ignored 为 true，虽然看起来你的伪代码是 设置了错误的 ignore

**Comment by ss7424Refar** [comment]
恩. 少了一个d. 
谢谢了.
