### ISSUE TITLE
接口请求报错，，但是返回是正常的

### ISSUE THREAD

**Issue by uncleMrWang** [simple-uploader/vue-uploader#161]
Access to XMLHttpRequest at 'http://192.168.0.191:18181/media/resource/upload' from origin 'http://192.168.0.222:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
浏览器报错如上

但是其他的都是正常的，使用这个上传插件就会这样，，但是数据是正常返回的
怎么不发送testMethod,测试了就是这个导致我的接口报错

**Comment by dolymood** [comment]
跨域了 基本前端知识 去搜下就知道了
