### ISSUE TITLE
取消cancel方法调用之后依然调用了fileAdded事件

### ISSUE THREAD

**Issue by hankaibo** [simple-uploader/vue-uploader#166]
我的需求是批量上传，但有数量限制。
我在change监听，当数量超过时，我调用了this.uploaderInstance.cancel()方法。this.uploaderInstance是它的实例。
虽然我取消了，但是fileadded事件依然被调用了。
请问我使用的方式不对吗？

**Comment by dolymood** [comment]
as https://github.com/simple-uploader/vue-uploader/issues/132
