### ISSUE TITLE
关于processResponse的使用

### ISSUE THREAD

**Issue by dxh007** [simple-uploader/vue-uploader#168]
我们项目后台是通过转发的。每个分片请求不管是否成功，http的status code都会返回200，然后再根据返回的data里面的code去判断具体情况，比如200代表该分片上传成功。这样导致的问题就是分片上传不管成功与否，插件都会认为是成功了。因为http的status code为200.现在我需要使用processResponse判断每个分片是否上传成功，如果返回的data里面的code不等于200，就是上传失败了，请问该怎么处理呢？
![image](https://user-images.githubusercontent.com/20332019/125051482-948f3080-e0d5-11eb-980a-a053fa987bb9.png)

**Comment by dolymood** [comment]
cb(err, res)
如果你是认为失败了 就 cb(true, res) 如果成功了 就 cb(null, res)
