### ISSUE TITLE
ios点击选择文件没反应

### ISSUE THREAD

**Issue by lwpassvoice** [simple-uploader/vue-uploader#17]
![image](https://user-images.githubusercontent.com/22510735/34369435-91b96912-eaf6-11e7-81ea-6475fd81ad23.png)
试着把源码里的button改成了label就可以了

**Comment by dolymood** [comment]
我拿了 iOS 11 的两个版本的 手机看了下 都是可以点击的 ，不知你的环境是怎样的

**Comment by lwpassvoice** [comment]
@dolymood 
我是在微信小程序的webview里试的，手机是6s和6
版本不太清楚。。

**Comment by dolymood** [comment]
建议还是真机上看下，我测试的时候，在原生浏览器测试了 也在微信中测试了；都没问题的

**Comment by lwpassvoice** [comment]
<uploader 
          id="uploader"
          ref="uploader"
          :simultaneousUploads="5"
          :options="options" 
          :autoStart="false" 
          :permanentErrors="[401, 404, 415, 500, 501]"
          @file-added="fileAdded"
          @files-submitted="filesSubmitted"
          @file-error="fileError"
          @file-success="fileSuccess"
          @complete="complete">
          <uploader-unsupport>不支持此功能，请升级微信或浏览器</uploader-unsupport>
          <uploader-btn>选择文件</uploader-btn>
        </uploader>

![image](https://user-images.githubusercontent.com/22510735/39104286-4d33cf06-46e2-11e8-964e-7b9eb69e125e.png)

你好，代码如上，ios6s, 11.1.2
在微信中点击时常点击无反应，浏览器要双击才行
我在<uploader>最外层加了label标签，ios直接点击没反应，web上单击就可弹出选框

这个也能看出区别
http://runjs.cn/code/wlmsh7fe

**Comment by lwpassvoice** [comment]
@dolymood

**Comment by dolymood** [comment]
https://github.com/simple-uploader/Uploader/blob/develop/src/uploader.js#L343

assignBrowse 是有这样的逻辑在里边的，你把demo也加上这样的逻辑试试

**Comment by lwpassvoice** [comment]
嗯加上assignBrowse的逻辑demo是正常的

这个代码
`
    <uploader 
      id="uploader"
      ref="uploader">
      <uploader-unsupport>不支持此功能，请升级微信或浏览器</uploader-unsupport>
      <uploader-btn>选择文件</uploader-btn>
    </uploader>
`
在pc上，要双击才能选文件；
Android正常；
6s，11.1.2没反应。。。

**Comment by lwpassvoice** [comment]
@dolymood

**Comment by dolymood** [comment]
11.0.1 的系统 Safari 我试了没问题，我这没 11.1.2 的系统，所以测试不了，你可以连接电脑Safari调试下

**Comment by lwpassvoice** [comment]
请问你是用的example里的做的测试吗，我用11.1.2试下  @dolymood

**Comment by hasbug** [comment]
IOS9.x   IOS10.3.3出现此问题，选择文件后没后续。

**Comment by dolymood** [comment]
最新版本还有问题？

**Comment by hasbug** [comment]
@dolymood  0.5.2有  我换回0.5.0就可以正常使用

**Comment by dolymood** [comment]
@hasbug  我试了下 10.3.1 没问题

**Comment by hasbug** [comment]
@dolymood 不是吧 我的是5C  10.3.3 和公司测试机是9.x，具体多少那天没看。我装了0.5.2，有问题，装0.5.0没问题，发现是点击上传的标签差异在 0.5.2是label，0.5.0是span。
