### ISSUE TITLE
什么时候更新 npm 包？

### ISSUE THREAD

**Issue by niluni1** [simple-uploader/vue-uploader#172]
npm 可以更新至 vue3 吗？

**Comment by dolymood** [comment]
参考 https://github.com/simple-uploader/vue-uploader/tree/vue3

可以安装 next tag 的版本目前处于 beta 版本

@ygj6  提供支持

**Comment by wangsongc** [comment]
请问vue3正式版本有发布计划吗？ 目前看到最新的是beta.5 @dolymood
