### ISSUE TITLE
vue3.0 Cannot read property '_c' of undefined

### ISSUE THREAD

**Issue by xubuhang** [simple-uploader/vue-uploader#174]
你好，vue3.0中引入vue-simple-uploader中后，显示有uploader的页面报错。信息如下：
![image](https://user-images.githubusercontent.com/4189632/133539330-9877d469-7f23-4fee-bb60-b958a260c4da.png)

**Comment by Wykyoyo** [comment]
你好,我也遇到了相同的问题,请问解决了吗

**Comment by ygj6** [comment]
0.7.6版本还不支持vue3，所以有这个报错，可以拉vue3分支的代码用用
https://github.com/simple-uploader/vue-uploader/tree/vue3

**Comment by LiangMD** [comment]
请问下，拉取vue3代码后该怎么用呢？

**Comment by LiangMD** [comment]
你好，我也遇见了相同的问题，麻烦问下解决了吗？

**Comment by dolymood** [comment]
参考 https://github.com/simple-uploader/vue-uploader/tree/vue3

可以安装 next tag 的版本目前处于 beta 版本

@ygj6  提供支持
