### ISSUE TITLE
vue3.0版本是不是少方法

### ISSUE THREAD

**Issue by zll-one** [simple-uploader/vue-uploader#180]
vue3.0版本里面file.pause(),file.cancel()方法都无效

**Comment by zll-one** [comment]
file.cancel()取消这个方法没有效果

**Comment by xxasd** [comment]
和vue版本无关，方法都是simple-uploader内的实例

**Comment by zll-one** [comment]
> 和vue版本，方法都是simple-uploader内的实例

vue3版本不能直接使用取消的

**Comment by xxasd** [comment]
报错信息有吗

**Comment by zll-one** [comment]
问题我已经解决取消方法必须在proxy里使用才有效，我把file加入proxy在使用就行了

**Comment by zll-one** [comment]
> 报错信息有吗

问题我已经解决取消方法必须在proxy里使用才有效，我把file加入proxy在使用就行了

**Comment by dolymood** [comment]
参考 https://github.com/simple-uploader/vue-uploader/tree/vue3

可以安装 next tag 的版本目前处于 beta 版本

@ygj6  提供支持
