### ISSUE TITLE
如何上传指定分片

### ISSUE THREAD

**Issue by xxasd** [simple-uploader/vue-uploader#182]
现在有个情况，前端按顺序传递分片的时候，假设传递 [1, 2, 3, 4, 5, 6] 其实都传递成功了，后端处理的时候只处理了 [1, 2, 4]，后端直接返回下次上传需要传递的分片 [3, 5, 6]，下次上传的时候想只上传 [3, 5, 6] 分片，查了好久文档好像找不到可以满足的方法

**Comment by xxasd** [comment]
已找到方法，通过检测 `preprocess` 的 `chunk.preprocessFinished()` 来控制哪一片需要上传

**Comment by fade24away** [comment]
可以控制第一块分片首先上传，中间的分片并发上传，最后一块分片最后上传吗

**Comment by Uqhs** [comment]
> 已找到方法，通过检测 `preprocess` 的 `chunk.preprocessFinished()` 来控制哪一片需要上传
你好，请问我要如何在preprocess里面怎么控制当前分片 是上传还是跳过呢，求解，感谢感谢
