### ISSUE TITLE
并发上传控制上传顺序

### ISSUE THREAD

**Issue by fade24away** [simple-uploader/vue-uploader#191]
在并发上传时，可以控制第一块先上传，中间部分并发上传，最后一块最后上传

**Comment by dolymood** [comment]
如果使用checkUploadedByResponse的话，默认就是只会发第一个块的，然后根据结果进行后续的上传
至于最后一个块 我理解应该没影响了

这个还是需要服务端控制下，要不然失去了并发的意义
