### ISSUE TITLE
如何上传第二个文件，自动覆盖第一个文件？

### ISSUE THREAD

**Issue by jefferyjob** [simple-uploader/vue-uploader#198]
文档里面提到的 `singleFile` 限制上传一个文件，指的的每次只能上传一个。
我的需求不只是每次只能上传一个，如果上传第二个则需要把第一个图片资源覆盖，这样保证 **始终只能上传一个给服务器**

**Comment by jefferyjob** [comment]
咋给我关闭了

**Comment by dolymood** [comment]
自己实现这个逻辑即可
在我理解 没大的差异
