### ISSUE TITLE
vue3使用时element-plus和uploader冲突

### ISSUE THREAD

**Issue by mini317** [simple-uploader/vue-uploader#199]
![image](https://user-images.githubusercontent.com/90594513/187168748-85336eca-b359-478c-af4d-25cd458077c1.png)

**Comment by dolymood** [comment]
vue3 用 next tag 的beta 版本才可以

**Comment by mini317** [comment]
> 

用的确实是beta版本

**Comment by dolymood** [comment]
那不应该出现访问_c出现

这个只在vue2版本会出现

用最新的beta版本
