### ISSUE TITLE
IE11 报错，不同浏览器看到的请求数不一致

### ISSUE THREAD

**Issue by zhangzeting1314** [simple-uploader/vue-uploader#2]

**Comment by dolymood** [comment]
意思是一个文件夹，里边有三个文件，但是在 360 中发送4次请求 是这样吧？

**Comment by zhangzeting1314** [comment]
是的，而且本地用ie11 跑，报错，不支持啊，不是支持到ie10+吗？？

**Comment by dolymood** [comment]
ie跑的话 需要加上这个 ，之前的示例是没在 IE 下跑的

可以参考这个修改 ，把example下的也 include ，https://github.com/simple-uploader/vue-uploader/commit/ec0e3a2596264037a8e7d840d777690455510fb4

360 的我在看下

**Comment by dolymood** [comment]
关于 options 请求策略，不同浏览器，不同版本还不大一样，chrome 60的效果是并发的三次 options 之后不再请求了；而 firefox55则是每个都会发options

**Comment by zhangzeting1314** [comment]
配置的相关文档中没有设定请求方式的吗？上传文件携带的参数，如何设置，事例也没有，比较迷惑

**Comment by dolymood** [comment]
关于设定请求方式？跨域才会发 options 请求 和什么请求没关系，这属于浏览器行为

关于配置文档里已经写了 参考 https://github.com/simple-uploader/Uploader#configuration

**Comment by dolymood** [comment]
已加了中文 https://github.com/simple-uploader/vue-uploader/blob/master/README_zh-CN.md

关于配置可以参考 https://github.com/simple-uploader/Uploader/blob/develop/README_zh-CN.md#%E9%85%8D%E7%BD%AE

**Comment by zhangzeting1314** [comment]
嗯谢谢，不过在使用前，看了下配置，需要同步修改服务端，实现分块上传，有时候需求服务端不能同步修改，前端用这个此插件，如何设置能实现文件一次上传，不分块

**Comment by dolymood** [comment]
可以考虑把 chunkSize 设置超大就好了

**Comment by zhangzeting1314** [comment]
我也想过，那项目里试一试吧，然后反馈一下情况
