### ISSUE TITLE
文件夹验证是否存在bug

### ISSUE THREAD

**Issue by xieyuxaing** [simple-uploader/vue-uploader#20]
@files-submitted="filesAdd"

filesAdd(fileList){
                console.log("2222222");
                console.log(fileList);
                for(var f in fileList){
                    if(fileList[f].size > 5 * 1024){
                        this.$message({
                        message: '存在单文件5K以上文件，请重新选择文件！',
                        type: 'error',
                        duration: 2000
                    });
                        break;
                    }
                }
                for(var n in fileList){
                    fileList[n].ignored = true;
                }
            }

还是可以继续上传

**Comment by dolymood** [comment]
目前只存在于对 file-added 的处理，暂时还没对 files-added 做处理。

这个我后续改下，如果着急的话，可以先用 file-added 处理
