### ISSUE TITLE
vue3版本uploader.value.uploader实例对象可以获取，方法调用undefined

### ISSUE THREAD

**Issue by changbb** [simple-uploader/vue-uploader#213]
vue3中使用1.0.0-beta.5版本有以下问题
` const uploader = ref(null)
//这里正常打印
  console.log(uploader, '======uploader======')
//这里正常打印
   console.log(uploader.value, 'uploader.value')
//这里正常打印
console.log(uploader.value.uploader, 'uploader.value.uploader')
下面的方法都是undefined
console.log(uploader.value.uploader.resume())
console.log(uploader.value.uploader.upload())
`
无法手动触发内部方法

**Comment by dolymood** [comment]
之前的文档有问题 参考新的描述  https://github.com/simple-uploader/vue-uploader/blob/vue3/README_zh-CN.md#appvue

**Comment by changbb** [comment]
> 
我是按照这个demo进行验证的，需求是在fileAdd事件中调用uploaderRef.value.uploader.pause()暂停上传，处理好参数以后uploaderRef.value.uploader.resume()再次发起上传，这里的这两个方法都是undefined，是无法使用的

**Comment by changbb** [comment]
> 之前的文档有问题 参考新的描述 https://github.com/simple-uploader/vue-uploader/blob/vue3/README_zh-CN.md#appvue

我是按照这个demo进行验证的，需求是在fileAdd事件中调用uploaderRef.value.uploader.pause()暂停上传，处理好参数以后uploaderRef.value.uploader.resume()再次发起上传，这里的这两个方法都是不起作用的

**Comment by changbb** [comment]
`<template>
  <uploader
    :options="options"
    :file-status-text="statusText"
    class="uploader-example"
    ref="uploaderRef"
    @file-added="fileAdd"
    @file-complete="fileComplete"
    @complete="complete"
  >
    
  </uploader>
</template>

<script>
  import { nextTick, ref, onMounted } from 'vue'
  export default {
    setup() {
      const uploaderRef = ref(null)
      const options = {
        target: '/api/v1/videos/chunk-upload', // '//jsonplaceholder.typicode.com/posts/',
        testChunks: false,
      }
      const attrs = {
        accept: 'image/*',
      }
      const statusText = {
        success: 'success',
        error: 'error',
        uploading: 'uploading',
        paused: 'paused',
        waiting: 'waiting',
      }
      const complete = () => {
        console.log('complete', arguments)
      }
      const fileComplete = () => {
        console.log('file complete', arguments)
      }
      const fileAdd = (file) => {
        console.log(uploaderRef.value, 'uploader.value')
        console.log(uploaderRef.value.uploader, 'uploader.value.uploader')
        console.log(uploaderRef.value.uploader.pause())
        //undefined
        console.log(uploaderRef.value.uploader.resume())
        // undefined
        // 方法不触发
        uploaderRef.value.uploader.pause()
      }
      onMounted(() => {
        nextTick(() => {
          window.uploader = uploaderRef.value.uploader
        })
      })
      return {
        uploaderRef,
        options,
        attrs,
        statusText,
        complete,
        fileComplete,
        fileAdd,
      }
    },
  }
</script>

<style>
  .uploader-example {
    width: 880px;
    padding: 15px;
    margin: 40px auto 0;
    font-size: 12px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.4);
  }
  .uploader-example .uploader-btn {
    margin-right: 4px;
  }
  .uploader-example .uploader-list {
    max-height: 440px;
    overflow: auto;
    overflow-x: hidden;
    overflow-y: auto;
  }
</style>
`

**Comment by changbb** [comment]
`
 const fileAdd = (file) => {
        console.log(uploaderRef.value, 'uploader.value')
        console.log(uploaderRef.value.uploader, 'uploader.value.uploader')
        console.log(uploaderRef.value.uploader.pause())
        //undefined
        console.log(uploaderRef.value.uploader.resume())
        // undefined
        // 方法不触发
        uploaderRef.value.uploader.pause()
      

> }

`
