### ISSUE TITLE
vue3 版本的 @file-added 事件会触发两次

### ISSUE THREAD

**Issue by xakoy** [simple-uploader/vue-uploader#215]
```vue
 <uploader
    :options="options"
    :file-status-text="statusText"
    class="uploader-example"
    ref="uploaderRef"
    @file-complete="fileComplete"
    @file-added="fileAdd"
    @complete="complete"
  ></uploader>
```

```
function fileAdd() {
        console.log('file add')
}
```
结果会打印两次。

看了你的代码，可能是从vue2迁移过来的，vue3的props改版了，事件也会包含在props中。所以会触发两次。

<img width="398" alt="image" src="https://user-images.githubusercontent.com/8230415/223028417-baec814a-8d8b-4ab5-bc27-b6146f91ac84.png">

**Comment by xakoy** [comment]
看了PR，是这两周添加出来的问题：
https://github.com/simple-uploader/vue-uploader/commit/8c5d55c1dfb3051db2f3d7a976dad2763b6c995d

现在临时的解决方法是再加一:on-file-added="beforeFileAdded"，这样的属性，而且必须放在@file-added后面。
```
<uploader
    :options="options"
    :file-status-text="statusText"
    class="uploader-example"
    ref="uploaderRef"
    @file-complete="fileComplete"
    @file-added="fileAdd"
    :on-file-added="beforeFileAdded"
    @complete="complete"
  ></uploader>
```

希望改进一下，谢谢。

**Comment by dolymood** [comment]
1.0.1 修复
建议使用 `:onFileAdded="onFileAdded"`
