### ISSUE TITLE
报错：this.xhr.upload.addEventListener is not a function

### ISSUE THREAD

**Issue by fanyoufu** [simple-uploader/vue-uploader#22]
this.xhr.upload.addEventListener is not a function

**Comment by dolymood** [comment]
能提供个 demo 什么的复现吗 例如可以在 codesandbox codepen 之类的上边

**Comment by fanyoufu** [comment]
可能是其它的问题导致的。现在并没有再次遇到这个问题。

**Comment by wencaizhang** [comment]
遇到同样的问题，经过排查，发现和引入 Mock.js 有关（我的项目是这样），取消引入 Mock.js  的代码就可以正常使用了。

**Comment by codexu** [comment]
顶楼上
