### ISSUE TITLE
Vue3.4兼容性问题

### ISSUE THREAD

**Issue by LibraLkm** [simple-uploader/vue-uploader#228]
升级Vue3.4之后，会出现上传进度数字为无穷大，上传进度底色样式丢失的问题

**Comment by senyuan1135** [comment]
同感，百分比一直为Infinity%
![image](https://github.com/simple-uploader/vue-uploader/assets/25975888/f8608c06-7561-4deb-96f1-ebf42c3bfddc)

**Comment by SoberK** [comment]
求解决：百分比一直为Infinity%

**Comment by fengxiongmiao** [comment]
![Xnip2024-04-30_13-18-01](https://github.com/simple-uploader/vue-uploader/assets/55432722/e3f8f23f-a0f3-4dff-9bff-8db39f1836f7)
这行代码反复执行造成的计算结果infinity，希望作者能尽快修复一下，谢谢🙏

**Comment by cheen77** [comment]
同样遇到这个问题

**Comment by ArtisticOpalescent** [comment]
同样遇到这个问题

**Comment by hidewnd** [comment]
同样遇到问题，希望作者修复下🙏

**Comment by dolymood** [comment]
1.0.3 已经修复
