### ISSUE TITLE
本地开发正常，打包部署上线后，选择文件就报错无法，有解决方案吗

### ISSUE THREAD

**Issue by md-wsm** [simple-uploader/vue-uploader#236]
![C %725LPRVOW_NU9T9NLQVP](https://github.com/user-attachments/assets/172d3b7d-98d7-441d-951f-4cc0069f95f4)
![15A4042 %ZFBTO~ZPP7ZF13](https://github.com/user-attachments/assets/3f748243-22d3-421a-a14c-e4835e6dc839)

**Comment by songkungz** [comment]
我也遇到了相同的问题，请问这个问题你解决了么
