### ISSUE TITLE
Uploader is undefined after Vue.use

### ISSUE THREAD

**Issue by Liniik** [simple-uploader/vue-uploader#26]
As mentioned in usage, I have this:
import Vue from 'vue'
import App from './App'
Vue.use(uploader)

new Vue({
    el: '#mountPoint',
    router,
    template: '<App/>',
    components: { App },
})

But when I try to use it in another single file component like this:
export default {
    name: 'upload',
    mounted(){
        const uploaderInstance = this.$refs.uploader.uploader
        console.log(uploaderInstance)
    }
}
I get only Error in mounted hook: "TypeError: Cannot read property 'uploader' of undefined".
I tried to import it before export default:
import uploader from 'vue-simple-uploader'
export default{...} and use it like uploader.files but I still got only undefined. Am I missing something or is it a bug and I have to register it somehow else?

**Comment by dolymood** [comment]
Can you show your full .vue component file ?

**Comment by Liniik** [comment]
Sure, here it is
[https://gist.github.com/Liniik/4cb81df803f1a73c7a6c44dee9609bbb](url)

**Comment by dolymood** [comment]
https://gist.github.com/Liniik/4cb81df803f1a73c7a6c44dee9609bbb#file-uploadvideo-vue-L11

Here you need to add `ref="uploader"`  so you can get `this.$refs.uploader`

For more details, https://vuejs.org/v2/guide/components.html#Child-Component-Refs 
 https://vuejs.org/v2/api/#ref

**Comment by Liniik** [comment]
I'm still struggling with other things but this solved it (now I see it is also in example...), thank you.
