### ISSUE TITLE
Need SSR support

### ISSUE THREAD

**Issue by vsorrokin** [simple-uploader/vue-uploader#27]
Is is easy - first need to make simple-uploader.js module make to support SSR, I did this in fork https://github.com/vsorrokin/Uploader/commit/860f0fe9349718ce23262e9a5bf3ccc1237962fc

And second - you need to provide in dist es6 module version of lib without using of window. For now I just import src/index.js from your lib

**Comment by dolymood** [comment]
0.5 support
