### ISSUE TITLE
图标识别不出来

### ISSUE THREAD

**Issue by xuchao321** [simple-uploader/vue-uploader#31]
![1523844985 1](https://user-images.githubusercontent.com/28084523/38787277-a8d842b6-415f-11e8-8c0c-0997363d301f.jpg)
![1523845029 1](https://user-images.githubusercontent.com/28084523/38787278-a923e388-415f-11e8-979e-7654e5c27f3c.jpg)
我那个是俩个竖线

**Comment by xuchao321** [comment]
@dolymood 您好 有具体写法 可以贴出代码吗

**Comment by dolymood** [comment]
参考

https://github.com/simple-uploader/vue-uploader/blob/master/src/components/file.vue#L356-L378
