### ISSUE TITLE
相同的class样式覆盖不掉问题 谢谢

### ISSUE THREAD

**Issue by xuchao321** [simple-uploader/vue-uploader#34]
![1524792988 1](https://user-images.githubusercontent.com/28084523/39340119-e5e2aece-49fe-11e8-9944-58ee7f639aa7.jpg)
![1524793012 1](https://user-images.githubusercontent.com/28084523/39340121-e6bf5b26-49fe-11e8-94dd-63553da2425c.jpg)

**Comment by xuchao321** [comment]
![1524794481 1](https://user-images.githubusercontent.com/28084523/39340669-fc5fb018-4a01-11e8-8ea1-f732f4f5a3fb.jpg)
大佬 这个也覆盖不掉啊  ..

**Comment by dolymood** [comment]
scope 就是这个规则

**Comment by lwpassvoice** [comment]
试试这个？
https://blog.csdn.net/csdn_yudong/article/details/79087236
