### ISSUE TITLE
form中点击导致页面刷新

### ISSUE THREAD

**Issue by pianfeng240** [simple-uploader/vue-uploader#35]
点击前 http://localhost:7067/#/home/fileEdit
点击选择按钮后，页面刷新，http://localhost:7067/?#/home/fileEdit

将npm dist中的button改为span，正常。

![image](https://user-images.githubusercontent.com/11719252/39664294-acb076c0-50b3-11e8-95f5-b8c82a6df0a2.png)

**Comment by lwpassvoice** [comment]
同https://github.com/simple-uploader/vue-uploader/issues/17

**Comment by dolymood** [comment]
0.4.6 修复。Thanks！
