### ISSUE TITLE
如何批量删除文件

### ISSUE THREAD

**Issue by lvzhu** [simple-uploader/vue-uploader#37]
需要如下操作： 
     this.$refs.uploader.uploader.fileList=[];
      this.$refs.uploader.uploader.files=[];
      this.$refs.uploader.fileList=[];
      this.$refs.uploader.files=[];
-----------为什么需要同时清除uploader.uploader 和 uploader呢？？？？

请博主给予回复。 3ku

**Comment by dolymood** [comment]
uploader.uploader 有cancel 方法可以使用。

这个只是对 uploader 的一点封装，带UI，其他的方法都需要自己调用 uplader.uploader 得到Uploader实例去操作。

关于更多用法，可参考文档，https://github.com/simple-uploader/Uploader/blob/develop/README_zh-CN.md
