### ISSUE TITLE
options不是响应式的

### ISSUE THREAD

**Issue by nathon-wang** [simple-uploader/vue-uploader#38]
options不是响应式的，只在create的时候赋值了，这样如果要动态改变option.query，没有任何效果，不能设置上传时的动态参数

**Comment by dolymood** [comment]
query 可以是函数，参考文档 https://github.com/simple-uploader/Uploader/blob/develop/README_zh-CN.md#%E9%85%8D%E7%BD%AE

**Comment by hasbug** [comment]
@dolymood 需求有点不一样，需要在fileadd回调里面去修改query，可以做到么？

**Comment by fengyutingg** [comment]
> @dolymood 需求有点不一样，需要在fileadd回调里面去修改query，可以做到么？

现在有这个需求，不知道您是怎么解决的
