### ISSUE TITLE
没有找到文件上传完成的回调方法

### ISSUE THREAD

**Issue by LeeJunhui** [simple-uploader/vue-uploader#4]
在Uploader组件上没有找到文件上传完成的事件

**Comment by dolymood** [comment]
升级到 0.2.0 

用法可以参考 https://github.com/simple-uploader/vue-uploader/blob/master/example/App.vue#L2

文档的话这里 https://github.com/simple-uploader/vue-uploader/blob/master/README_zh-CN.md#事件
