### ISSUE TITLE
怎么判断  什么时候开始拖拽的   有没有什么标志或者属性？

### ISSUE THREAD

**Issue by Paul-Yellow** [simple-uploader/vue-uploader#43]
因为我需要拖拽的时候，接受的区域为整个页面，而不是页面中的那一小块。所以我想监听客户何时拖动，然后显示组件中拖拽区域的蒙层。

**Comment by dolymood** [comment]
如果是这个页面的话，我建议手工 assignDrop 来做，可以通过 `uploader.uploader` 获取Uploader实例，然后assignDrop 就可以。

蒙层效果的话，可以参考 https://github.com/simple-uploader/vue-uploader/blob/master/src/components/drop.vue 的实现。

后续的话，我这边会考虑把彼此组件间关系拆开，这样灵活性更高。

**Comment by Paul-Yellow** [comment]
这个问题解决了  但是还有个新的问题   就是  autoStart=false 浏览器会挂   多点几下就会出现这个问题

**Comment by Paul-Yellow** [comment]
在拖拽的情况下 会出现这个bug 不是拖拽没事

**Comment by dolymood** [comment]
是多点几下 还是多拖拽几下

**Comment by Paul-Yellow** [comment]
拖拽进去  然后删掉   然后在点击拖拽进去   就不好使了

**Comment by dolymood** [comment]
0.5 相对应的 simple-uploader.js@0.3 的版本新增了 change dragover dragenter dragleave drop 事件可以做状态控制
