### ISSUE TITLE
上传文件时连续打开两次选择框，第一次选择无效

### ISSUE THREAD

**Issue by msidolphin** [simple-uploader/vue-uploader#46]
![11111](https://user-images.githubusercontent.com/26672484/44318309-d3fd9c00-a467-11e8-95ea-379f5ab1251b.gif)

触发了两次click事件，第二次选择文件后才会触发change事件

**Comment by hasbug** [comment]
同样遇到这个问题

**Comment by msidolphin** [comment]
@hasbug https://github.com/simple-uploader/Uploader/pull/12

**Comment by hasbug** [comment]
作者还没合并发布npm···

**Comment by dolymood** [comment]
0.3.2 fixed this
