### ISSUE TITLE
能否单选文件？发现个关于fileAdd的问题。

### ISSUE THREAD

**Issue by hasbug** [simple-uploader/vue-uploader#49]
咱们貌似没有字段进行限制input表单的multiple属性？

然后，目前我给自己上传组件传入一个数值，告诉组件剩余可传文件数，例如：maxCounts:0 ,然后我在file-added设置  
```javascript
if(this.maxCounts==0){
        Toast('图片已达上限')
        file.ignored = true
      }
```
，按住ctrl进行多选文件，选择数量超过1个，点击完成添加，但并未提示，而是直接全部开始上传了。

**Comment by dolymood** [comment]
UploaderBtn 有 attrs 属性可以添加的

**Comment by hasbug** [comment]
@dolymood 设置了multiple:false (或者multiple:'')貌似都是存在多选。

**Comment by dolymood** [comment]
sorry 其实是 btn 的 single Prop 决定的
