### ISSUE TITLE
在Dialog消失之后，如何将上传组件状态重置呢？

### ISSUE THREAD

**Issue by LeeJunhui** [simple-uploader/vue-uploader#5]
**Element**自带的组件的话，可以使用
`this.$refs.xxxForm.resetFields();`
来进行重置。
但是**vue-uploader**有提供类似的方法吗？

**Comment by dolymood** [comment]
hey，我加到文档里了，可以得到 Uploader 实例，然后调用其 cancel() 方法就行

https://github.com/simple-uploader/vue-uploader/blob/master/README_zh-CN.md#得到-uploader-实例
