### ISSUE TITLE
fileSuccess触发的时机

### ISSUE THREAD

**Issue by hasbug** [simple-uploader/vue-uploader#50]
我发现在分块上传的场景下，假如分为3块，有时候并不是第三块才触发，而是可能是前面的块，我发现可能第三块上传完成了  其他的可能还在上传中。
我的项目这边目前是所有块上传完成后才进行合并，不是最后一块的话，一般都返回200状态而已，只有第三块才返回上传后的结果url。如果在其他块触发了fileSuccess，那么，我就错过了后端的返回结果。

**Comment by hasbug** [comment]
如果并发大于1就会这样

**Comment by dolymood** [comment]
这个后端逻辑改下不就完了 和前端无关的，前端肯定保证不了完成顺序的
