### ISSUE TITLE
又来求助，上传完后合并

### ISSUE THREAD

**Issue by hasbug** [simple-uploader/vue-uploader#53]
如果我希望是全部上传完后，在fileComplete单独发起一个异步请求进行合并，得到结果后再将上传结束，能做到吗？
我看到有processResponse，这个方法能在fileComplete中再调用吗，还是说可以通过某个钩子去等待fileComplete中的合并回调后再触发processResponse？

**Comment by dolymood** [comment]
为何需要浪费一次进行合并呢，关于后端demo可以参考 flow 或者 resumable 的示例都可以。

你说的那个是不可以的。

**Comment by hasbug** [comment]
谢谢！

**Comment by fjh1997** [comment]
直接通过GET /download/:identifier 下载不就可以合并了？
