### ISSUE TITLE
How to use dynamic target which is dependent on a selectbox

### ISSUE THREAD

**Issue by pkdq** [simple-uploader/vue-uploader#61]
I've the options as follows :

```
return {
      url: '/api/upload/product',
      options: {
        target: null,
        testChunks: false,
        singleFile: true,
        chunkSize: 1e+9,
      },
      attrs: {
        accept: ['.csv', '.xls', '.xlsx'],
      },
      product: null,
      items: [
        'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten',
      ],
    };


watch: {
    product(value) {
      console.log('WATCH : ', value);
      this.options.target = `${this.url}/${value}`;
    },
  },
```

The target is getting changed if I check in VueDev Tools, but on uplading files it is setting the call as : 

/api/upload/product/null

**Comment by dolymood** [comment]
The `target` could be a function, you can return real upload target URL.

https://github.com/simple-uploader/Uploader#configuration

**Comment by dongyidongyi1111** [comment]
I have the same problem. Have you solved it?

**Comment by shady-xia** [comment]
先拿到Uploader实例，然后它的 `opts` 属性就是实例的配置项对象
Get the Uploader instance first, then its `opts` property is the instance configuration object of the Uploader.

` this.$refs.uploader.uploader.opts.target = '//:your url'`
