### ISSUE TITLE
Show error message from backend

### ISSUE THREAD

**Issue by maxotto** [simple-uploader/vue-uploader#63]
I try to use vue-uploader with YII-1 backend.
I want to inform a user about why the server side cannot upload a file. For example, such file exists, or file is too big and so on. User should to know the reason exactly.
Backend responses with code 417, for example, and JSON like this: 
`{"success":false,"message": "File is too big"}`

How can I show my "File is too big" message instead of simple "error" which comes from statusText object?
Thank you.

**Comment by dolymood** [comment]
After 0.6.0, you can set `Uploader` prop `fileStatusText` to be a function, like:
```js
fileStatusText(status, response) {
  const statusTextMap = {
    uploading: 'uploading',
    paused: 'paused',
    waiting: 'waiting'
  }
  if (status === 'success' || status === 'error') {
    // only use response when status is success or error

    // eg:
    // return response message ?
    return response.message
  } else {
    return statusTextMap[status]
  }
}
```

**Comment by Sakthi002** [comment]
thank you sir.

**Comment by maxotto** [comment]
Thank you :)
