### ISSUE TITLE
Is there any way by which i could be able to redesign components?

### ISSUE THREAD

**Issue by Awais-cb** [simple-uploader/vue-uploader#64]
i need to redesign ` <uploader-list></uploader-list>` component is there any possible way to do this?

**Comment by Awais-cb** [comment]
@dolymood

**Comment by dolymood** [comment]
Maybe you can use Slot ?

**Comment by Awais-cb** [comment]
I was able to inject my own html into `<uploader-list>` and had access to fileList using `slot-scope` but still i am unable to access `<uploade-file>` and its binded date any possible way to customize ui of `<uploader-file>`

**Comment by dolymood** [comment]
Maybe you can your own `UploaderFile` component like https://github.com/simple-uploader/vue-uploader/blob/master/src/components/file.vue .

Or use the default `<uploader-file>` with scoped slots, but can not handle the `pause/resume/remove...` action, maybe i need to add the action methods to the slot scope of  `<uploader-file>`.
