### ISSUE TITLE
Send post data with each file

### ISSUE THREAD

**Issue by Awais-cb** [simple-uploader/vue-uploader#65]
is there any possible way to send $_POST array containing file data like file name,file description,file tags etc with each uploaded file? @dolymood

**Comment by dolymood** [comment]
Sorry. Can you please give me a demo to show the case ?

**Comment by Awais-cb** [comment]
![screenshot from 2018-12-06 11-36-39](https://user-images.githubusercontent.com/27766561/49566083-4331ca00-f94b-11e8-8829-a66308c65c3d.png)
Basically this is what i am trying to do i wan't to post some data right after upload this this is an example of plupload i am trying to something same with your uploader
