### ISSUE TITLE
nuxt1.4 版本引用当前插件使用时报错关于export default events   ^^^^^^   SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by tuotuogenjudi** [simple-uploader/vue-uploader#66]
nuxt1.4 版本引用当前插件使用时,页面启动或者刷新，报错关于export default events   ^^^^^^   SyntaxError: Unexpected token export@dolymood @sandrew

**Comment by dolymood** [comment]
感觉是安装的出了问题，入口是编译后的代码，这个包不存在 export default 的逻辑
