### ISSUE TITLE
请问fileParameterName这个配置项必须作为请求参数吗？

### ISSUE THREAD

**Issue by A-yi** [simple-uploader/vue-uploader#68]
请问fileParameterName这个配置项必须作为请求参数传给后台吗？是否可以取消掉呢？
![image](https://user-images.githubusercontent.com/29707448/52849170-5df29d00-314b-11e9-9a18-50ae88561908.png)

**Comment by dolymood** [comment]
那是文件的内容，去掉了 还上传啥

**Comment by A-yi** [comment]
那这样是不是后台也需要配置呢？因为使用的是第三方接口，这种情况的话上传就会失败
