### ISSUE TITLE
你好，问下断点续传的问题

### ISSUE THREAD

**Issue by 364124337** [simple-uploader/vue-uploader#69]
使用testChunks 后，在
target: (...args)=>{
            if(args[2]){
              return `xxx/mgr/getTaskProgress.do`
            }else{
              return `xxx/mgr/uploadPart.do`
            }
          },
在checkChunkUploadedByResponse处理好后，使用第二个接口（xxx/mgr/uploadPart.do）上传为啥第一块没有上传了？急急急！！！

**Comment by 364124337** [comment]
求大佬解释下！

**Comment by 364124337** [comment]
testMethod:'POST'  是否 testMethod :'PUT'要为这个

**Comment by dolymood** [comment]
这个地方可能会有点问题，但是目前的话，应该还是根据的状态码来决定是否已经上传了，且之后的文件也是采用采用相同的状态去判断的。这个我在下个大版本更新。

目前的话可以使用 processResponse 来强制更改。

**Comment by dolymood** [comment]
issue 地址 https://github.com/simple-uploader/Uploader/issues/38

**Comment by 364124337** [comment]
testChunks 为true 请求后，请求返回已上传块接口（xxx/mgr/getTaskProgress.do）不触发processResponse函数  ，更改不了状态码

**Comment by 364124337** [comment]
在checkChunkUploadedByResponse函数里边更改为args[0].file.chunks[0].xhr.status = 5050   这样不行

**Comment by dolymood** [comment]
> testChunks 为true 请求后，请求返回已上传块接口（xxx/mgr/getTaskProgress.do）不触发processResponse函数 ，更改不了状态码

在test的case下确实不行，修改 xhr status 肯定是不行的 因为不允许

**Comment by 364124337** [comment]
ok，think you!

**Comment by dolymood** [comment]
0.7 解决了这个问题 checkChunkUploadedByResponse 会决定第一块上不上传也
