### ISSUE TITLE
请问如何让attrs的accept属性动态生效？

### ISSUE THREAD

**Issue by shady-xia** [simple-uploader/vue-uploader#80]
现在是这样的，我封装了一个全局的上传组件，然后在系统不同的地方允许的上传格式不同，我动态更改attrs的accept属性，发现并没有动态生效，仍然是初始的状态

我看了下uploader-btn组件，只在mounted里面调用了一次assignBrowse，请问怎么实现这种动态变更accept属性的效果？

**Comment by dolymood** [comment]
默认不支持动态，如果非得动态，估计只有获取到对应input元素 然后修改其属性了。

**Comment by cqkd6381** [comment]
看来对动态参数的需求很高啊，望作者能够提供 @dolymood ，感谢~
