### ISSUE TITLE
同时多个文件上传时，后面文件的额外参数会覆盖之前的。

### ISSUE THREAD

**Issue by 947247807** [simple-uploader/vue-uploader#85]
同时多个文件上传时，后面文件的额外参数会覆盖之前的。需要单独做保存，回收处理。不知道对不对0.0

**Comment by 947247807** [comment]
问题所在是175-177行代码导致。我的处理是在options中添加一个querys，onFileAdded时在querys中记录文件名和对应的params，然后在options的query函数中根据文件名取出并返回params，最后文件上传成功时记得delete掉记录的params

**Comment by dolymood** [comment]
麻烦提供代码示例

**Comment by 947247807** [comment]
175-177// 添加额外的参数this.uploader.opts.query = { ...this.params} ， 每次计算MD5之后都会对option中的query进行赋值新对象。如果选取的上一个文件没传完（上传中），而下一个文件已经计算完MD5并开始上传（这是query被赋予新值），那么上一个文件后续的上传片取得query就是新值了。

**Comment by 947247807** [comment]
option: {
    ...
    query: function(file, chunk, isTestChuncks) {
                        // console.log(file, chunk, isTestChuncks)
                        return file.uploader.opts.querys[file.name] || {}
                    },
                    querys: {} //记录上传文件的额外参数 上传完删除相应的记录
}
----
this.options.querys[file.name] = params 
---
delete file.uploader.opts.querys[file.name]
写的比较拉，见谅。

**Comment by dolymood** [comment]
对于query的动态修改，不支持这种方式，如果是动态修改，就在query函数中处理

**Comment by dolymood** [comment]
至于MD5的部分，参考 https://github.com/simple-uploader/vue-uploader/issues/15

**Comment by 947247807** [comment]
感谢。

**Comment by 947247807** [comment]
( ⊙ o ⊙ )啊！刚发现自己写错地方了，感谢大佬认真对待。好尴尬..

**Comment by tjthink** [comment]
> ( ⊙ o ⊙ )啊！刚发现自己写错地方了，感谢大佬认真对待。好尴尬..

兄弟你怎么解决的，我也遇到这个问题了，指点一下
