### ISSUE TITLE
上传文件小于分块大小时，只请求了第一次get请求，并没有发送文件

### ISSUE THREAD

**Issue by 314833234** [simple-uploader/vue-uploader#86]
上传文件小于分块大小时，只请求了第一次get请求，并没有发送文件

**Comment by dolymood** [comment]
https://github.com/simple-uploader/Uploader/blob/develop/README_zh-CN.md#%E5%A4%84%E7%90%86-get-%E6%88%96%E8%80%85-test-%E8%AF%B7%E6%B1%82
