### ISSUE TITLE
请问在fileSuccess事件中怎么改变当前文件的状态？比如分块上传完成后，请求分块合并接口时，后端返回合并失败，此时前端显示状态需要变成上传失败。

### ISSUE THREAD

**Issue by 314833234** [simple-uploader/vue-uploader#88]

**Comment by dolymood** [comment]
参数 processResponse 处理就可以 参考配置中的 https://github.com/simple-uploader/Uploader/blob/develop/README_zh-CN.md#%E9%85%8D%E7%BD%AE

第一个参数 err
