### ISSUE TITLE
上传错误

### ISSUE THREAD

**Issue by lyj0823** [simple-uploader/vue-uploader#91]
无论上传什么文件都提示出错了是怎么回事呢？有没有人遇到过这个问题，谢谢1

**Comment by lyj0823** [comment]
![捕获](https://user-images.githubusercontent.com/39751573/61675581-82baf400-ad2b-11e9-95b6-0dfff7deadf1.PNG)

**Comment by lyj0823** [comment]
Hi, when I run this project, I get the result such as above? Do you know why?

**Comment by dolymood** [comment]
对应的serve部分是用的 https://github.com/simple-uploader/Uploader/tree/develop/samples/Node.js  对应的服务 默认是没起的
