### ISSUE TITLE
上传文件过大的时候 并发上传不好用 请问是在前台做限制 还是在后台做限制

### ISSUE THREAD

**Issue by yuehui1** [simple-uploader/vue-uploader#92]

**Comment by Lollipopls** [comment]
如何解决的呢

**Comment by yuehui1** [comment]
并发上传是假的&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lollipopls"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 中午11:02
收件人:&nbsp;"simple-uploader/vue-uploader"<vue-uploader@noreply.github.com&gt;;
抄送:&nbsp;"哦哈哦哈哦哈"<1783808546@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [simple-uploader/vue-uploader] 上传文件过大的时候 并发上传不好用 请问是在前台做限制 还是在后台做限制 (#92)




如何解决的呢
